server:
  port: 8888

spring:
  zipkin:
    enabled: true
    base-url: http://loscalhost:9411
    service:
      name: config-server
  profiles:
    active: native #native lokalde çalıştırıyoruz demek oluyor.
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
