server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EticaretAuthDB
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

#ÖNEMLİ
# SecretKey ve Issuer gibi başkalarının görmesini ulaşmasını istemeyeceğimiz verileri sınıfımızda ya da yml dosyasında dahi tutmak sakıncalıdır.
# Bundan dolayı bu bilgileri gizlememiz gereklidir. Bu bilgileri gizlemek için Environment Variable(Ortam Değişkenleri) kullanılabilir.
# Denetim masasından sistem ortam değişkenleri düzenle kısmından ortam değişkenlerini seçerek yeni diyip key-value şeklinde ekleme yapıyoruz.
# JAVA12_ISSUER -> Java12 ve JAVA12_SECRETKEY -> r56EWAKpd665uryNgcByz0kTDzUgfynftIoa4FQgT9FwtGVi8C gibi ekleyebiliriz.
# Eklediğimiz environment variable kullanımında yml dosyamıza artık sadece key( ${key} şeklide ) kısımlarını yazıyoruz ve value kısımlarını gizlemiş oluyoruz.
# JwtTokenManager içinde de @Value("${authserviceconfig.secrets.secret-key}") şeklinde ikisine de Value işaretleyerek yml dosyamızdaki yolu veriyoruz.
# Bu işlemi yapınca sistem hata veriyor programı kapatıp açınca kendine geliyor.

#2.YOL: Projeye sağ tıklayıp More Run/Debug->Modify Run Configuration diyoruz ve Environment Variables kısmına Key-Value olarakta ekleyebiliyoruz.
#Proje içine eklediğimizde Denetim Masasından ulaştığımız Environment Variable içine ekleme yapmıyor.
#Environment Variable çağırdığımız zaman oradan getiriyormuş gibi getiriyor. Kullanıcı değil proje bazlı ortam değişkeni gibi tutuyor.

#3.YOL: Projeye environmentvar.bat dosyası açıp içine setx ler ile yine key value olarak ekliyoruz.
#Terminal kısmından .\environmentvar.bat enter diyerek Environment Variable olarak denetim masası ortam değişkenlerine ekliyor.
authserviceconfig:
  secrets:
    secret-key: ${JAVA12_SECRETKEY}
    issuer: ${JAVA12_ISSUER}

